name: Feature request
description: If an app experiences issues with AdGuard that cannot be resolved using standard filter lists
labels: "Feature request"
body:
  - type: input
    id: platform
    attributes:
      label: Platform
      description: What platform are you running?
      placeholder: For example, Android
    validations:
      required: true
